TopSneakers/TopSneakers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('menu.urls')),
    path('AppProductos/', include('AppProductos.urls'))
]

TopSneakers/carro/urls.py
from django.urls import path

from .import views

app_name="carro"

urlpatterns = [
   
   
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", views.restar_producto, name="restar"),
    path("limpiar/", views.limpiar_carro, name="limpiar"),
   
    
]

TopSneakers/menu/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import test, stayloyal, sobrenosotrosadmin,registrarse , sobrenosotros, pumasnea, pu_4, pu_3, pu_2, pu_1, productosadmin,productos, privacidad, perfil, perfiladmin, pago, nikesnea, menuadmin, jordansmoke, jordanair1mid, iniciosesion, inicioadmin, histoordenes, envioypago, elegir, contactosadmin, contactanos, carritoadmin, carrito, airforce, adidassnea, ad_4, ad_3, ad_2, ad_1, modificar, recuperar,agadmin
from . import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [

    path('registrarse',views.registrarse, name='registrarse'),
    path('test/',views.test, name='test'),
    path('stayloyal/',views.stayloyal, name="stayloyal"),
    path('sobrenosotrosadmin/',views.sobrenosotrosadmin, name='sobrenosotrosadmin'),
    path('sobrenosotros/',views.sobrenosotros, name='sobrenosotros'),
    path('pumasnea/',views.pumasnea, name='pumasnea'),
    path('pu_4/',views.pu_4, name='pu_4'),
    path('pu_3/',views.pu_3, name='pu_3'),
    path('pu_2/',views.pu_2, name='pu_2'),
    path('pu_1/',views.pu_1, name='pu_1'),
    path('productosadmin/',views.productosadmin, name='productosadmin'),
    path('productos/',views.productos, name='productos'),
    path('privacidad/',views.privacidad, name='privacidad'),
    path('perfil/',views.perfil, name='perfil'),
    path('perfiladmin/',views.perfiladmin, name='perfiladmin'),
    path('pago/',views.pago, name='pago'),
    path('nikesnea/',views.nikesnea, name='nikesnea'),
    path('menuadmin/',views.menuadmin, name='menuadmin'),
    path('jordansmoke/',views.jordansmoke, name='jordansmoke'),
    path('jordanair1mid/',views.jordanair1mid, name='jordanair1mid'),
    path('',views.iniciosesion, name='iniciosesion'),
    path('inicioadmin/',views.inicioadmin, name='inicioadmin'),
    path('histoordenes/',views.histoordenes, name='histoordenes'),
    path('envioypago/',views.envioypago, name='envioypago'),
    path('elegir/',views.elegir, name='elegir'),
    path('contactosadmin/',views.contactosadmin, name='contactosadmin'),
    path('contactanos/',views.contactanos, name='contactanos'),
    path('carritoadmin/',views.carritoadmin, name='carritoadmin'),
    path('carrito/',views.carrito, name='carrito'),
    path('airforce/',views.airforce, name='airforce'),
    path('modificar/',views.modificar, name='modificar'),
    path('adidassnea/',views.adidassnea, name='adidassnea'),
    path('ad_4/',views.ad_4, name='ad_4'),
    path('ad_3/',views.ad_3, name='ad_3'),
    path('ad_2/',views.ad_2, name='ad_2'),
    path('ad_1/',views.ad_1, name='ad_1'), 
    path('recuperar/',views.recuperar, name='recuperar'),  
    path('admin/',views.admin, name='admin'), 
    path('carro/',include('carro.urls')),
    path('agadmin/',views.agadmin, name='agadmin')

    
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TopSneakers/menu/models.py
from django.db import models

# Create your models here.
class Detalle(models.Model):
    id_detalle = models.AutoField(primary_key=True)
    cantidad_detalle = models.IntegerField(blank=False, verbose_name='Cantidad detalle')
    subtotal_detalle = models.IntegerField(blank=False, verbose_name='Subtotal detalle')

    def __str__(self):
        return str(self.id_detalle)
    

class Compra(models.Model):
    id_compra = models.AutoField(primary_key=True)
    detalle = models.ForeignKey(Detalle, on_delete=models.CASCADE, related_name='compras')
    f_compra = models.DateField(blank=False, verbose_name='Fecha de compra')
    f_retiro = models.DateField(blank=False, verbose_name='Fecha retiro')
    estado_compra = models.CharField(max_length=40, blank=False, verbose_name='Estado de la compra')
    total = models.IntegerField(blank=False, verbose_name='Total de la compra')
    carrito_compra = models.CharField(max_length=100)

    def __str__(self):
        return str(self.id_compra)

    
class Usuario(models.Model):
    id_usuario = models.AutoField(primary_key=True)
    rut_usuario = models.IntegerField(blank=False, verbose_name='Ingrese su rut')
    nombre_usuario = models.CharField(max_length=20, blank=False, verbose_name='Ingrese su nombre')
    apellido_usuario = models.CharField(max_length=20, blank=False, verbose_name='Ingrese su apellido')
    correo_usuario = models.EmailField(max_length=40, blank=False, verbose_name='Ingrese su correo')
    contraseña_usuario = models.CharField(max_length=40, blank=False)
    respuesta_usuario = models.CharField(max_length=150, blank=False, verbose_name='Respuesta', default='default value')

    def __str__(self):
        return str(self.rut_usuario)

    
class Rol(models.Model):
    id_rol = models.OneToOneField(Usuario, primary_key=True, on_delete=models.CASCADE)
    nombre_rol = models.CharField(max_length=50, blank=False, verbose_name='Nombre Rol')

    def __str__(self):
        return self.nombre_rol

    
class Pregunta(models.Model):
    id_pregunta = models.OneToOneField(Usuario, primary_key=True, on_delete=models.CASCADE)
    nombre_pregunta = models.CharField(max_length=100, blank=False, verbose_name='Pregunta')

    def __str__(self):
        return self.nombre_pregunta

class CategoriaProd(models.Model):
    nombre = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name="categoria"
        verbose_name_plural="categorias"

    def __str__(self):
        return self.nombre

class Producto (models.Model):
    nombre = models.CharField(max_length=50)
    categoria = models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='menu', null=True, blank=True)
    descripcion_producto = models.CharField(max_length=150, blank=False, verbose_name='Descripcion producto')
    talla_producto = models.IntegerField(blank=False, verbose_name='Talla de producto')
    stock_producto = models.IntegerField(blank=False, verbose_name='Stock producto')
    precio_producto = models.IntegerField(blank=False, verbose_name='Precio producto')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="producto"
        verbose_name_plural="productos"

TopSneakers/menu/forms.py
from django import forms
from .models import Usuario
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['first_name','last_name','email','password1','password2']

TopSneakers/menu/views.py
from django.shortcuts import render, redirect
from .models import Producto
from django.views.generic import View
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from .forms import CustomUserCreationForm

# Create your views here.
    
def registrarse(request):
    data = {
        'form': CustomUserCreationForm()
    }
    return render(request, 'menu/registrarse.html', data)

def post(self, request):
        form=UserCreationForm(request.POST)

        if form.is_valid():

            Usuario=form.save()

            login(request, Usuario)

            return redirect('test.html')
        
        else:
            pass



def test(request):
    return render (request,'menu/test.html')

def productos(request):

    productos=Producto.objects.all()

    return render (request,'menu/productos.html',{"productos":productos})

def productosadmin(request):

    productos=Producto.objects.all()

    return render(request,'menu/productosadmin.html',{"productosadmin":productos})   

def stayloyal(request):
    return render (request,'menu/stayloyal.html')

def sobrenosotrosadmin(request):
    return render (request,'menu/sobrenosotrosadmin.html')

def sobrenosotros(request):
    return render (request,'menu/sobrenosotros.html')


def pumasnea(request):
    return render (request,'menu/pumasnea.html')

def pu_4(request):
    return render (request,'menu/pu_4.html')

def pu_3(request):
    return render (request,'menu/pu_3.html')

def pu_2(request):
    return render (request,'menu/pu_2.html')

def pu_1(request):
    return render (request,'menu/pu_1.html')


def privacidad(request):
    return render (request,'menu/privacidad.html')

def perfiladmin(request):
    return render (request,'menu/perfiladmin.html')

def perfil(request):
    return render (request,'menu/perfil.html')

def pago(request):
    return render (request,'menu/pago.html')

def nikesnea(request):
    return render (request,'menu/nikesnea.html')

def menuadmin(request):
    return render (request,'menu/menuadmin.html')

def jordansmoke(request):
    return render (request,'menu/jordansmoke.html')

def jordanair1mid(request):
    return render (request,'menu/jordanair1mid.html')

def iniciosesion(request):
    return render (request,'menu/iniciosesion.html')

def inicioadmin(request):
    return render (request,'menu/inicioadmin.html')

def histoordenes(request):
    return render (request,'menu/histoordenes.html')

def envioypago(request):
    return render (request,'menu/envioypago.html')

def elegir(request):
    return render (request,'menu/elegir.html')

def contactosadmin(request):
    return render (request,'menu/contactosadmin.html')
def contactanos(request):
    return render (request,'menu/contactanos.html') 

def carritoadmin(request):
    return render (request,'menu/carritoadmin.html')
def carrito(request):
    return render (request,'menu/carrito.html')

def airforce(request):
    return render (request,'menu/airforce.html')

def modificar(request):
    return render (request,'menu/modificar.html')

def adidassnea(request):
    return render (request,'menu/adidassnea.html')

def ad_4(request):
    return render (request,'menu/ad_4.html')

def ad_3(request):
    return render (request,'menu/ad_3.html')

def ad_2(request):
    return  render(request,'menu/ad_2.html')

def ad_1(request):
    return render (request,'menu/ad_1.html')

def recuperar(request):
    return render (request,'menu/recuperar.html')
def admin(request):
    return render (request,'menu/admin.html')
def agadmin(request):
    return render (request,'menu/agadmin.html')

TopSneakers/menu/templates/menu/ad_2.html
{% extends 'menu/plant_zapa.html'%}
{% load static %}

{% block titulo%}adidasedge{% endblock %}
{% block foto1 %}<img src="{% static 'menu/img/adidas edge lux 2.jpg'%}" class="d-block w-100" alt="foto1">{% endblock %}
{% block foto2 %}<img src="{% static 'menu/img/zapatillas-adidas-edge-lux-2.jpg'%}" class="d-block w-100 " alt="foto2">{% endblock %}
{% block foto3 %}<img src="{% static 'menu/img/zapatillas-adidas-edge-lux-2 (1).jpg'%}" class="d-block w-100" alt="foto3">{% endblock %}
{% block nombrezapa %}<h3 style="font-family: 'Courier New', Courier, monospace;color: rgb(0, 0, 0);">Adidas Edge Lux 2</h3>{% endblock %}
{% block preciozapa %}<h3 style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;color: rgb(0, 0, 0);">$69.990</h3>{% endblock %}
{% block desczapa %}<h4>Consigue tus objetivos marcados con un diseño cómodo y flexible. Esta zapatilla de running se ha confeccionado con una horma específica para mujer que se adapta a tu pisada, incorpora la tecnología BOUNCE</h4>{% endblock %}
{% block cantzapa %}<p>Stock:6</p>{% endblock %}

TopSneakers/menu/templates/menu/ad_4.html
{% extends 'menu/plant_zapa.html'%}
{% load static %}

{% block titulo%}adidascsmash{% endblock %}
{% block foto1 %}<img src="{% static 'menu/img/courtsmash.png'%}" class="d-block w-100" alt="foto1">{% endblock %}
{% block foto2 %}<img src="{% static 'menu/img/coutsmash2.png'%}" class="d-block w-100 " alt="foto2">{% endblock %}
{% block foto3 %}<img src="{% static 'menu/img/courtsmash3.png'%}" class="d-block w-100" alt="foto3">{% endblock %}
{% block nombrezapa %}<h3 style="font-family: 'Courier New', Courier, monospace;color: rgb(0, 0, 0);">Adidas Courtsmash</h3>{% endblock %}
{% block preciozapa %}<h3 style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;color: rgb(0, 0, 0);">$44.990</h3>{% endblock %}
{% block desczapa %}<h4>Estas zapatillas tienen un diseño ligero perfecto para devolver saques complicados. Diseñadas para tenistas aficionados, incorporan un exterior de cuero sintético resistente al desgaste.</h4>{% endblock %}
{% block cantzapa %}<p>Stock:4</p>{% endblock %}

TopSneakers/menu/templates/menu/contactanos.html
{% extends 'menu/plant_menuusu.html'%}
{% load static %}

{% block titulo %} contacto {% endblock %}



{% block relleno %}
   <div class="container w-75 bg-light mt-5 rounded shadow rounded-end p-5" style="position:relative; top:70px;">
     <div class="row align-items-stretch">
       
         
         <h1 class="fw-bold text-center py-n5" style="position:relative; top:-50px;"> ¿Deseas contactarnos? </h1>
          <h3>Envianos tu mensaje</h3>
         <form action="#">
          <div class="mb-1">
            <label for="nombre" class="form-label">Nombre completo</label>
            <input type="text" class="form-control"  id="nombre">
         </div>
            <div class="mb-1">
              <label for="correo" class="form-label">Correo electronico</label>
              <input type="text" class="form-control" id="correo" name="correo">
           </div>
           <div class="mb-1">
            <label for="mensaje" class="form-label">Mensaje</label>
            <input type="text" class="form-control" id="mensaje" name="mensaje">
         </div>
             <br>
               <div class="d-grid">
                <input type="submit" onclick=" return Enviar();" value="Enviar mensaje"> 
               </div>
         </form>

        </div>
        
     </div>
   
   {% endblock %}
    <script src="{% static 'menu/js/validaciones.js'%}"></script>
   

TopSneakers/menu/templates/menu/contactosadmin.html
{% extends 'menu/plant_admin.html'%}
{% load static %}
{% block titulo %}contacto{% endblock %}
{% block relleno %}

   <div class="container w-75 bg-light mt-5 rounded shadow rounded-end p-5" style="position:relative; top:70px;"
   >
     <div class="row align-items-stretch">
       
         <div class="text-end" >
            
         </div>
         <div class="container-fluid color-container1 ">

         </div>
 
         <div class="d-flex  justify-content-center my-n2">

            <img src="{% static 'menu/img/logo.png'%}" class="img-fluid my-n1" style="position:relative; top:-50px;" alt="" width="250">
          </div>
         <h1 class="fw-bold text-center py-n5" style="position:relative; top:-50px;"> ¿Deseas contactarnos? </h1>
          <h3>Envianos tu mensaje</h3>
          <form action="#">
            <div class="mb-1">
              <label for="nombre" class="form-label">Nombre completo</label>
              <input type="text" class="form-control"  id="nombre">
           </div>
              <div class="mb-1">
                <label for="correo" class="form-label">Correo electronico</label>
                <input type="text" class="form-control" id="correo" name="correo">
             </div>
             <div class="mb-1">
              <label for="mensaje" class="form-label">Mensaje</label>
              <input type="text" class="form-control" id="mensaje" name="mensaje">
           </div>
               <br>
                 <div class="d-grid">
                  <input type="submit" onclick=" return Enviar();" value="Enviar mensaje"> 
                 </div>
           </form>

        </div>
        <div class="col">

        </div>
     </div>
   </div>
   {% endblock %}
   
<script src="{% static 'menu/js/validaciones.js'%}"></script>
 

TopSneakers/menu/templates/menu/envioypago.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/iniciosesion.css">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/estilo.css">
    <link rel="stylesheet" href="css/fontello.css">
    <link rel="stylesheet" href="css/fondo.css">
    <link rel="stylesheet" href="css/tablas.css">
    <title>Envio y pago</title>
</head>
<body>
            <!-- menu -->
            <nav class="navbar navbar-expand-md navbar-light  fixed-top">
                <div class="container container-color ">
                  <a href="test.html" style="color: rgb(173, 6, 6);" class="navbar-brand"><span >TOP<img src="img/iconozapa.png" height="20px" width="20px" alt=""></span><h5 class="h5-fo1">SNEAKERS</h5>
                          
                         
                  </a>
                  
                  <button class="navbar-toggler " 
                   data-bs-toggle="collapse" 
                   data-bs-target="#mainNav" 
                   aria-controls="mainNav"
                   aria-expanded="false" 
                   aria-label="toggle navigation">
                          <span style="color: rgb(173, 6, 6);" class="icon-menu "></span>
                  </button>
                 <div class="collapse navbar-collapse " id="mainNav">
                          <ul class="navbar-nav ms-auto mb-2 mb-md-0 "style="position: relative;">
                                  <li >
                                          
                                          <div class="buscar">
                                                  <input type="text" placeholder="Buscar" required />
                                            
                                                  <div class="btn btn-1">
                                                    <i  class="fas fa-search icon-search "></i>
                                                  </div>
                                          </div>                  
                                  </li>
                                  <li>
                                          <div>
                                                  <a href="carrito.html" class="nav-link a1 " ><img src="img/carrito.png" alt="carrito" height="15px" width="20px"></i></a>
                                          </div>
                                 </li> 
                                  <li >
                                           <a href="test.html" class="nav-link a1">INICIO</a>
                                  </li>
                                  <li >
                                          <a href="productos.html" class="nav-link a1">PRODUCTOS</a>
                                          
                                 </li>
                                 <li >
                                           <a href="contactanos.html" class="nav-link a1">CONTACTO</a>
                                                  
                                  </li> 
                                  <li >
                                          <a href="sobrenosotros.html" class="nav-link a1">SOBRE NOSOTROS</a>
                                 </li>  
                                            
                                 <li>             
                                          <div>
                                                <a href="perfil.html" class="nav-link a1">CUENTA</a>  
                                          </div>
                                 </li>  
                          </ul>
                
               
                  </div>
                </div>
          </nav>
          <footer class=" text-lg-start">
                
                <div class="container-fluid p-4 cont-foot">
                  
                  <div class="row">
                    
                    <div class="col-sm-12 mb-4 mb-md-0 colorin">
                      <h3 style="font-family: 'Courier New', Courier, monospace;" class="text-center">Gracias por ver</h3>
              
                      <p style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;" >
                        MENSAJES DE LOS CREADORES:
                        <br>
                        SIGAN EN TWITCH :
                        <a href="https://www.twitch.tv/arohbknight"> AROHBKNIGHT</a>
                        <br>
                        CRISTOBAL: Xd
                        <br>
                        SEBA: Borrenme el lol porfavor
                      </p>
                    
                    
                </div>
              
                
                <div class="text-center p-3" style="border: 2px solid rgb(173, 6, 6);background-color: rgb(177, 177,177 );" >
                  © 2023 Copyright :
                  <br>
                  <a href="test.html" style="color: rgb(173, 6, 6);" class="navbar-brand"><span >TOP<img src="img/iconozapa.png" height="20px" width="20px" alt=""></span><h5 class="h5-fo1">SNEAKERS</h5>
                        
                       
                  </a>
                </div>
                </div>
                 
                </div>   
        </footer> 
</body>
</html>

TopSneakers/menu/templates/menu/productos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static 'menu/img/jordanicon.png' %}">
    <link rel="stylesheet" href="{% static 'menu/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'menu/css/estilo.css' %}">
    <link rel="stylesheet" href="{% static 'menu/css/fontello.css' %}">
    
    <title>Producto</title>
</head>
<body>
         <!-- menu -->
         <nav class="navbar navbar-expand-md navbar-light  fixed-top">
          <div class="container container-color sm-12 md-12 lg-6 xl-6 ">
            <a href="{% url 'test'%}" style="color: rgb(173, 6, 6);" class="navbar-brand"><span >TOP<img src="{% static 'menu/img/iconozapa.png' %}" height="20px" width="20px" alt=""></span><h5 class="h5-fo1">SNEAKERS</h5>
                    
                   
            </a>
            
            <button class="navbar-toggler " 
             data-bs-toggle="collapse" 
             data-bs-target="#mainNav" 
             aria-controls="mainNav"
             aria-expanded="false" 
             aria-label="toggle navigation">
                    <span style="color: rgb(173, 6, 6);" class="icon-menu "></span>
            </button>
           <div class="collapse navbar-collapse " id="mainNav">
                    <ul class="navbar-nav ms-auto mb-2 mb-md-0 "style="position: relative;">
                            <li >
                                    
                                    <div class="buscar">
                                            <input type="text" placeholder="Buscar" required />
                                      
                                            <div class="btn btn-1">
                                              <i  class="fas fa-search icon-search "></i>
                                            </div>
                                    </div>                  
                            </li>
                            <li>
                                    <div>
                                            
                                            <a href="{% url 'carrito'%}" class="nav-link a1 " ><img src="{% static 'menu/img/carrito.png' %}" alt="carrito" height="15px" width="20px"></i></a>
                                        
                                    </div>
                           </li> 
                            <li >
                                     <a href="{% url 'test'%}" class="nav-link a1">INICIO</a>
                            </li>
                            <li >
                                    <a href="{% url 'productos'%}" class="nav-link a1">PRODUCTOS</a>
                                    
                           </li>
                           <li >
                                     <a href="{% url 'contactanos'%}" class="nav-link a1">CONTACTO</a>
                                            
                            </li> 
                            <li >
                                    <a href="{% url 'sobrenosotros'%}" class="nav-link a1">SOBRE NOSOTROS</a>
                           </li>  
                                      
                           <li>             
                                    <div>
                                          <a href="{% url 'perfil'%}" class="nav-link a1">CUENTA</a>  
                                    </div>
                           </li>  
                    </ul>
          
         
            </div>
          </div>
    </nav>
    <!-- menu -->
    <!-- MARCAS-->      
    <div  class="container-fluid sm-12 md-12 lg-6 xl-6">

      <div  class="row">
        <div class="col-sm-4 img"  >
          <a href="#"><img src="{% static 'menu/img/nike-log.jpg' %}" alt="" ></a>
          <p></p>
        </div>
        <div class="col-sm-4 img "   >
           <a href="#"><img src="{% static 'menu/img/adidas-log.jpg' %}" alt=""  ></a>
          <p></p>
        </div>
        <div class="col-sm-4 img ">
          <a href="#"><img src="{% static 'menu/img/puma-log.png' %}" alt="" ></a> 
          <p></p>
        </div>
      </div>
    </div>
      <div class="row">
    </div>
    <div class="row">

      
      {% for producto in productos %}
      
          <div class="col-md-3">
      
          <div class="card" >
      
              <img src="{{producto.imagen.url}}" class="card-img-top">
      
              <div class="card-body" style="text-align: center;">
      
                  <h7 class="card-title">{{producto.nombre}}</h7>
      
                  <p class="card-text">&nbsp;${{producto.precio_producto}}</p>

                  <p class="card-text"><br>{{producto.descripcion_producto}}</p>

                  <p class="card-text">Stock disponible<br>{{producto.stock_producto}}</p>
      
      
              </div> 
              
              <div class="card-footer text-center">
      
                  <a href="{% url 'carro:agregar' producto.id %}" class="btn btn-success">Agregar al carro</a>
      
              </div>
      
          </div><!--card que se cierra-->
          
        </div>
        {% endfor %}
  </div>
  
  
    <footer class=" text-md-start">
                
      <div class="container-fluid p-4 cont-foot sm-12 md-12 lg-6 xl-6 ">
        
        <div class="row">
          
          <div class="col-sm-12 md-12 lg-6 xl-6 mb-4 mb-md-0 colorin">
            <h3 style="font-family: 'Courier New', Courier, monospace;" class="text-center">Gracias por ver</h3>
    
            <p style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;" >
              MENSAJES DE LOS CREADORES:
              <br>
              SIGAN EN TWITCH :
              <a href="https://www.twitch.tv/arohbknight"> AROHBKNIGHT</a>
              <br>
              CRISTOBAL: Xd
              <br>
              SEBA: Borrenme el lol porfavor
            </p>
          
          
      </div>
    
      
      <div class="text-center p-3" style="border: 2px solid rgb(173, 6, 6);background-color: rgb(177, 177,177 );" >
        © 2023 Copyright :
        <br>
        <a href="{% url 'test'%}" style="color: rgb(173, 6, 6);" class="navbar-brand"><span >TOP<img src="{% static 'menu/img/iconozapa.png'%}" height="20px" width="20px" alt=""></span><h5 class="h5-fo1">SNEAKERS</h5>
              
             
        </a>
      </div>
      </div>
       
      </div>   
</footer> 
<script src="{% static 'menu/js/bootstrap.bundle.min.js' %}"></script>
      
</body>
</html>

TopSneakers/menu/templates/menu/pu_1.html
{% extends 'menu/plant_zapa.html'%}
{% load static %}

{% block titulo%}pumars{% endblock %}
{% block foto1 %}<img src="{% static 'menu/img/puma RS x3 600.png'%}" class="d-block w-100" alt="foto1">{% endblock %}
{% block foto2 %}<img src="{% static 'menu/img/puma rs 2.png'%}" class="d-block w-100 " alt="foto2">{% endblock %}
{% block foto3 %}<img src="{% static 'menu/img/puma Rs 1.png'%}" class="d-block w-100" alt="foto3">{% endblock %}
{% block nombrezapa %}<h3 style="font-family: 'Courier New', Courier, monospace;color: rgb(0, 0, 0);">Puma RS X3 Level up</h3>{% endblock %}
{% block preciozapa %}<h3 style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;color: rgb(0, 0, 0);">$79.990</h3>{% endblock %}
{% block desczapa %}<h4>Es una zapatilla ligera que proporciona un alto rebote en cada una de vuestras rutinas. Presenta un sistema de sujeción trenzada para mayor ajuste.</h4>{% endblock %}
{% block cantzapa %}<p>Stock:30</p>{% endblock %}